### ISSUE TITLE
Please publish new version to npmjs

### ISSUE THREAD

**Issue by fstoerkle** [harm-less/angular-sticky#14]
Hey, thanks for this nice module.

Would you mind publishing the latest version (2.4) to npmjs.com?
Currently, version 1.1 is reported as latest version there:

![2016-08-01 09_39_13-angular-sticky-plugin](https://cloud.githubusercontent.com/assets/97024/17286776/e4ea7e56-57cb-11e6-9f42-6b55e1aa91de.png)

Let me know if I can help you there.

**Comment by harm-less** [comment]
Mm, I though a Grunt task I use took care of that. But from now on every release should be published to NPM automatically.
Version 0.2.4 I've published manually so you should be able to use it right now.

Thanks for reporting this, I'd have hardly found this myself ;)

**Comment by fstoerkle** [comment]
That was quick :) Thanks a lot!
