### ISSUE TITLE
Issues with Dynamic Content

### ISSUE THREAD

**Issue by jchambers462** [harm-less/angular-sticky#15]
I have a toolbar with anchor="bottom". The toolbar is located below a table that takes a few seconds to load. Before the table's data is loaded, the toolbar is rendered correctly, in the non sticky position. After the data is loaded and the table rows are rendered, the toolbar gets bumped down the page, out of view. The toolbar does not become sticky. Any recommendations?

**Comment by harm-less** [comment]
Hey, 
I think I do have a suggestion. You could use the ```drawOptions``` from [hlStickyElement](http://harm-less.github.io/angular-sticky/#/api/service/hl-sticky-element) with ```force``` set to ```true```. I think that should work. I could be triggered when you load promise had been completed.
