### ISSUE TITLE
requires jquery even though you mention its a pure javascript implementation.

### ISSUE THREAD

**Issue by reco** [harm-less/angular-sticky#22]
i am using angular 1.5.8

**Comment by KaleRoberts** [comment]
+ 1
Getting console errors
ReferenceError: $ is not defined

**Comment by reco** [comment]
any word? @harm-less

**Comment by harm-less** [comment]
Hello @KaleRoberts and @reco,
Sorry for the late response and the inconvience, but I think you'll find your answer [here](https://github.com/harm-less/angular-sticky/issues/18#issuecomment-307917013).

Good luck!
