### ISSUE TITLE
bug with width

### ISSUE THREAD

**Issue by krysztal** [harm-less/angular-sticky#24]
bad width after hide->show element (#element).
Problem with method (line 309):
`
                        function elementWidth() {
				return nativeEl.offsetWidth;
			}
`
because after hide this method set width to 0 and after show set always 0.

`<div id="element" style="width: 200px;">
    <div hl-sticky="" style="background-color: red">
       Test
    </div>
    <div>
        <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
        1
        <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
        2
        <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
    </div>
</div`

**Comment by harm-less** [comment]
Is this just to make your point or do you need such a high sticky element?
