### ISSUE TITLE
Replaces the element with a div

### ISSUE THREAD

**Issue by maryl** [harm-less/angular-sticky#25]
If You don't use a `<div>` as a element with the `hl-sticky` attribute it'll replace the element with it, so we can't use it with a ie. `<section>` element.

**Comment by Ginwu** [comment]
I have the same problem with a `thead` and `tfoot` inside a `table` element. So it doesn't work at all.
How can I make this work?

**Comment by harm-less** [comment]
I've taken a look and with a few, what now seem like obvious, modifications I think I resolved the issue. I've haven't tested it, but at least the directive doesn't replace the element you've applied it to. But in theory it should work. I could be mistaken, but adding it to a table is a different ballgame. 

Anyway, in version [0.4.1](https://github.com/harm-less/angular-sticky/releases/tag/v0.4.1) it no longer get replaced. Good luck with the implementation though, hopefully it works out :)
