### ISSUE TITLE
Immediately show sticky-element (bottom)

### ISSUE THREAD

**Issue by SRoddis** [harm-less/angular-sticky#29]
Hey, I have a problem. 

I want to show a button on the bottom of the page (sticky). When I scroll down the whole page (like 2000 px), then it should not be sticky anymore and be at its position. Everything works fine until now. The Problem is, the element shows just up, when I scroll. I tried to work with “always-sticky”, then it is visibly from the beginning, but it does not “unstick” at the bottom of the page. Is there a way, where I can tell the element to be visible right from the beginning? Without scrolling? 

Cheers, Sean Roddis

**Comment by harm-less** [comment]
Hello Sean,

I'm not sure you already tried, but from the sound of it you need to use a container. A demo can be found here:
http://harm-less.github.io/angular-sticky/#!/demo/container

So make sure the container you use spans the entire section you'd like to have your element sticky.

Hopefully that will get you going.
Harm

**Comment by SRoddis** [comment]
Hey Harm, 
thanks for the quick response. Nice library btw. :)
I have tried the approach with the container, but it did not help to solve the "problem/feature". 
I just made an example to show you the use case. 

http://jsfiddle.net/51bsbzL0/406/

Cheers, 
Sean

**Comment by harm-less** [comment]
Thanks for the kind words :)

I see now. It seems to fail on just one just pixel even after I've updated you fiddle with the following CSS:
```css
html, body {
  margin: 0;
}
```

Maybe I need to account for this one pixel in the code. I'll check it out soon.

**Comment by harm-less** [comment]
Actually, now that I think about it, it's doing it very wrong. It shouldn't matter if the top of the page is overlapping the container, it should be sticky anyway. It's only the bottom of the box that matters as the opposite is true for the `top` aligned sticky element.

I've never used the bottom sticky element myself before, so I guess that's why I missed it.

**Comment by dotKev** [comment]
https://github.com/harm-less/angular-sticky/pull/32 should resolve this issue.

**Comment by harm-less** [comment]
@SRoddis I released a new version that includes the fix from @dotKev for issue #32. Does this fix your problem?

**Comment by SRoddis** [comment]
@harm-less:
Hey, sorry for the late reply!

The new version fixes the Problem. Great work.
http://jsfiddle.net/51bsbzL0/407/

Thank you!

Cheers,
Sean
