### ISSUE TITLE
Not sticky when at top of page (window.scrollY = 0)

### ISSUE THREAD

**Issue by dotKev** [harm-less/angular-sticky#31]
An item is never sticky when at the top of a page when sticky should evaluate to `true`.

The best example is the demo [simple bottom anchor](http://harm-less.github.io/angular-sticky/#!/demo/simple-bottom). The item isn't sticky until the user starts to scroll, and goes away when at the top of the page.

**Comment by harm-less** [comment]
Thanks for your contribution!
Please confirm if you issue has been resolved.

**Comment by dotKev** [comment]
Didn't mean to leave this hanging! Thanks!
