### ISSUE TITLE
Page Jumps on click

### ISSUE THREAD

**Issue by frecklebit** [harm-less/angular-sticky#35]
When using this plugin, the page jumps down about 50px when clicking any element (or body) once the container is "stuck".

**Comment by harm-less** [comment]
Hello Adam,

You are using a [placeholder ](http://harm-less.github.io/angular-sticky/#!/api/directive/hl-sticky) (at `use-placeholder`)? If not, that's probably your issue.

Otherwise, can you make a Plunker so or something similar so I can see what the issue is?
