### ISSUE TITLE
Placeholder height doesn't change after dynamic height change of sticky element

### ISSUE THREAD

**Issue by nitinagwl** [harm-less/angular-sticky#36]
sticky element with dynamic addition of a DOM element increasing the height of the element didn't change the placeholder height. This started to happen with the latest release 0.4.2 (reverted back to 0.4.1 and it works fine).

**Comment by harm-less** [comment]
That's interesting, I think that never really worked even before the update, haha.
This is the only change between `0.4.1` and `0.4.2`: https://github.com/harm-less/angular-sticky/commit/860a44d07f9b8e37a9d5b11cf601774ec06a34c1

So I don't really understand how that influenced the problem you're facing now.

**Comment by nitinagwl** [comment]
:-) I guess its my good luck! Thanks.

**Comment by harm-less** [comment]
Might just be, I'm closing the issue for now 😉
