### ISSUE TITLE
The package should be published in the npm registery

### ISSUE THREAD

**Issue by valexiev** [harm-less/angular-sticky#6]

**Comment by harm-less** [comment]
You're right. I didn't do it yet because most of the front-end libraries are retrieved from Bower. But I guess you'll not be the first to ask this so I'll take a look at this tomorrow.

**Comment by valexiev** [comment]
I have already installed it with npm directly from the repo. But it would be more convenient if it is in the npm registry.

**Comment by harm-less** [comment]
As of now you can also install [Angular Sticky](https://www.npmjs.com/package/angular-sticky-plugin) using npm!
```sh 
npm install angular-sticky-plugin
```

**Comment by valexiev** [comment]
Great!
Thank you!
